---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pg.onestein.nl
  resources:
  - postgres
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - pg.onestein.nl
  resources:
  - postgresdatabases
  - postgresroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pg.onestein.nl
  resources:
  - postgresdatabases/finalizers
  - postgresroles/finalizers
  verbs:
  - update
- apiGroups:
  - pg.onestein.nl
  resources:
  - postgresdatabases/status
  - postgresroles/status
  verbs:
  - get
  - patch
  - update
