apiVersion: pg.onestein.nl/v1
kind: PostgresRole
metadata:
  labels:
    app.kubernetes.io/name: pg-resource-operator
    app.kubernetes.io/managed-by: kustomize
  name: role-sample
spec:
  postgresRef:
    name: postgres-sample
  name: role-sample
  attributes:
    - CREATEDB  
  passwordSecret:
    name: role-sample-secret
  passwordKey: password

